[workspace]
members = [
  "app/src-tauri",
  "crates/app-core",
  "crates/local-store",
  "crates/warframe-acquisition",
  "crates/warframe-domain",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "GPL-3.0-only"
rust-version = "1.85"
repository = "https://github.com/Deftera186/tennoscope"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "2"
zeroize = "1"

[profile.dev]
opt-level = 2
