[package]
name = "tennoscope"
version.workspace = true
description = "TennoScope local-first Warframe companion"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde.workspace = true
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
app-core = { path = "../../crates/app-core" }
local-store = { path = "../../crates/local-store" }
warframe-acquisition = { path = "../../crates/warframe-acquisition" }
warframe-domain = { path = "../../crates/warframe-domain" }

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"

[dev-dependencies]
tempfile = "3"
